- docker-compose.yml
- src/matchbox/server/Dockerfile
- src/matchbox/server/api.py
* Environment file added as an argument to the API container startup. 
* Lifespan function added in app to explicitly create the matchbox database when initialising the API.
Is the lifespan function necessary?
> Create database added to API startup

- docker-compose.yml
- src/matchbox/server/Dockerfile
We're deploying Matchbox to AWS, and so making changes that support that.
This splits the Dockerfile into stages
- A "base" stage that has the bulk of the the command/config
- A "dev" stage that has configuration for local development
- A "prod" stage that has the configuration for deployment
The dev and prod stages are kept deliberately minimal to try to make sure that the local dev environment is as close to production as possible. The key differences between them are that the "prod" stage uses the run mode of fastapi compared to the "dev" mode in the dev stage, also "prod" does not contain any environment variables, while "dev" copies them in from the local filesystem - something we definitely want to avoid when making a production image.
Looking through the changes and running …
> Split Dockerfile to stages for dev and prod

- src/matchbox/__init__.py
- src/matchbox/client/_logging.py
- src/matchbox/client/helpers/selector.py
- src/matchbox/client/models/linkers/splinklinker.py
- src/matchbox/client/results.py
- src/matchbox/common/logging.py
- src/matchbox/common/transform.py
- src/matchbox/server/postgresql/benchmark/cluster_pipeline.py
- src/matchbox/server/postgresql/utils/insert.py
- src/matchbox/server/postgresql/utils/query.py
- test/client/test_helpers.py
- test/fixtures/data.py
- uv.lock
* logger creation is centralised at one place
[Help reviewers know where to focus their efforts, or flag controversial decisions]
* [List any useful links]
> Centralise logging

- .gitignore
- README.md
- docker-compose.yml
- environments/datadog-agent-private-sample.env
- environments/datadog-agent-public.env
- pyproject.toml
- src/matchbox/server/Dockerfile
- uv.lock
We're improving the monitoring/alerting/debugging setup, and specifically integrating with Datadog that the department is moving towards.
In order to maintain reusability, Matchbox should continue to work without Datadog: it is an optional integration, both locally and when deployed.
This change:
1. Runs the Datadog agent when running locally via docker compose using the "monitoring" profile
2. Sends traces to it from the api application by wrapping its startup with ddtrace-run as the ENTRYPOINT specified in the Dockerfile. It runs the agent and ddtrace-run in all cases in order to keep the local environment as similar as possible to deployed, but to actually sent data to Datadog, a real DD_API_KEY must be set in .datadog-agent-private.env. and the "monitoring" profile used with docker …
> Run the Datadog agent for local dev and pass traces to it

- src/matchbox/client/_handler.py
- src/matchbox/client/dags.py
- src/matchbox/client/helpers/selector.py
- src/matchbox/common/exceptions.py
- src/matchbox/common/factories/entities.py
- src/matchbox/common/factories/sources.py
- src/matchbox/common/sources.py
- test/client/test_dags.py
- test/client/test_helpers.py
- test/common/factories/test_entity_factory.py
- test/common/factories/test_source_factory.py
- test/common/test_sources.py
- test/e2e/test_e2e.py
- test/server/api/test_routes.py
- uv.lock
We want to eventually be able to support more than one configuration for the same source. Thus, the source address won't be anymore a unique identifier in our system. To avoid having to pass a point of truth twice when querying, to `mb.select()` as well as `mb.query()`, selecting doesn't fetch the source anymore; that is deferred till later.
* `Selector` does not hold a source anymore, only an address and an engine
* `mb.select()` does not retrieve a source. Sources are retrieved by `mb.query()`
* Created `Source.check_columns()` method, and made it stronger. For example, it now checks the db_pk exists in the warehouse
* Moved `format_columns()` from `Source` to `SourceAddress`
* Moved the only_indexed parameter from `select()` to `query()` and flipped its behaviour. By default, it's set …
> Move source retrieval out of selectors

- pyproject.toml
- src/matchbox/server/Dockerfile
- uv.lock
* Added setuptools-scm as a build dependency
* Made the version dynamic in pyproject.toml
* Updated the Dockerfile to temporarily mount .git and use git describe to determine the current tag when building the image
* I believe every commit will now update the uv.lock, which is a bit annoying, but not much noisier than it is already? I suppose the alternative is to set up a custom version generator for setuptools-scm that just says something like 0.2.5+DEV instead of the full commit hash and date
* It also, by default, increments the version automatically in a speculative manner. E.g. if the current tag is 0.2.4, and your git repo is dirty, it will say it's a dev version of 0.2.5
* Took inspiration from: https://setuptools-scm.readthedocs.io/en/latest/usage/#with-dockerpodman
> Use git tags to dynamically infer version

- src/matchbox/common/db.py
- src/matchbox/server/postgresql/db.py
- uv.lock
* Implement connection pool for ADBC connections
* Rationalise Matchbox database interface
* Remove ADBC import (except for type checking) in `matchbox.common`
This will, rather annoyingly, produce a lot of Postgres warnings when running tests. Raised an issue here: 
https://github.com/apache/arrow-adbc/issues/2673
Using this recipe: https://arrow.apache.org/adbc/17/python/recipe/postgresql.html#connection-pooling-with-sqlalchemy
> Implement ADBC connection pool

- src/matchbox/client/extract.py
- test/client/test_extract.py
* Remove `matchbox.client.extract.sql_interface`, replacing it with a simpler `matchbox.client.extract.primary_key_map`
This is a temporary measure. Further tickets have been created to implement next steps:
- https://uktrade.atlassian.net/browse/MTCHBX-309?atlOrigin=eyJpIjoiOGY1MWVjZWZmZTdmNGYxZDhkOTE0OGQ0ZWJjMTViYmUiLCJwIjoiaiJ9
- https://uktrade.atlassian.net/browse/MTCHBX-310?atlOrigin=eyJpIjoiMzMzMmQxZGE4ZTI1NDUwMGExYzhiMTI1ODFkZGVkMmIiLCJwIjoiaiJ9
None
None
> Temporarily turn sql interface to single mapping table

- src/matchbox/client/extract.py
- src/matchbox/server/postgresql/adapter.py
- test/client/test_extract.py
- test/e2e/test_e2e.py
- test/server/test_adapter.py
* Support generating mapping for a single source
* Error explicitly when no source is available
* Make engine filter optional (no longer needed)
* Error explicitly when resolution matching name isn't found
I changed the name of a linker in the e2e tests because it makes it simpler to test the AirFlow pipeline.
None
None
> Handle edge cases around SQL interface auxiliary functions

- src/matchbox/client/_handler.py
- src/matchbox/client/models/models.py
- src/matchbox/common/dtos.py
- src/matchbox/server/api/main.py
- src/matchbox/server/api/routers/models.py
- src/matchbox/server/api/routers/resolutions.py
- src/matchbox/server/base.py
- src/matchbox/server/postgresql/adapter.py
- src/matchbox/server/postgresql/orm.py
- src/matchbox/server/postgresql/utils/db.py
- test/client/test_model.py
- test/server/api/routes/test_routes_main.py
- test/server/api/routes/test_routes_models.py
- test/server/test_adapter.py
* Generalised deletion of models to deletion of resolutions across client, API and adapter
* Cleaned up ORM definitions of deletion cascading behaviour
* We've lost some fidelity in the DTO operation type, i.e. whether we're updating truth or ancestors cache. My idea is that as part of [this ticket](https://uktrade.atlassian.net/jira/software/projects/MTCHBX/boards/1123?assignee=61570c67c669a60069356d3a&selectedIssue=MTCHBX-321) we'd create an update endpoint for resolution - a single one, not one for name, for description etc. And as such it won't make sense to separate different update operations. Thoughts?
* Improving the DB counts (e.g. `adapter.clusters.count()`) is tracked in [this ticket](https://uktrade.atlassian.net/browse/MTCHBX-336)
None.
* [SQLAlchemy docs on …
> Improve deletion of resolutions

- test/utils.py
This commit adds a simple function for uploading parquet files of datasets to a local instance of the matchbox warehouse.
> Basic parquet to warehouse function

- docs/client/link-data.md
- src/matchbox/client/dags.py
- src/matchbox/client/helpers/selector.py
- src/matchbox/common/db.py
- src/matchbox/common/factories/sources.py
- src/matchbox/common/sources.py
- test/client/test_dags.py
- test/client/test_helpers.py
- test/common/factories/test_source_factory.py
- test/common/test_sources.py
This PR stems from two problems:
* Too many requests are made to a location, caused by an after model validator that is called when a source config is initialised or attached to any other object
* Many requests cause too many connections to be opened at the same time, which causes an error
* Created a single, unambiguous way of setting credentials: once, at the location level
* Created a new factory method for source configs, which infers field types
* Removed the previous factory method for source configs, which wasn't used anywhere
* Improved query which infers field types from location
* Removed non-generator version of `Location.execute()` and `Source.query()`
* Removed generator version of `Source.hash_data()` and the `query()` helper
Because:
* We were making lazy calls to the DB …
> Improve way SourceConfig use connections

- src/matchbox/common/sources.py
- uv.lock
* Added an abstract sample method to location
* Updated sampling to use original logic from new with yield batch size one. 
Is there anywhere else we can benefit from applying this method. 
> Move sampling functionality to location method

- src/matchbox/common/hash.py
- src/matchbox/server/postgresql/utils/insert.py
- test/common/test_hash.py
Caching model results wasn't working because ID order doesn't matter when rationalising about whether two sets of probabilities evaluate to the same clusters, but it _does_ matter when making the hash.
This PR adds a `normalise` argument to Arrow table hashing that lets you declare columns whose order can be ignored when hashing. This is basically the solution I used in #190 to show that a change in the methodology hadn't changed the results it produced.
* Adds normalisation to `hash_arrow_table()` and uses it in `matchbox.server.postgres.utils.insert.insert_results()`
* Totally refactors the sprawling unit tests of the function so they're a bit more organised
I know I didn't have to refactor the unit tests but when I added coverage for normalisation the file became hard work to read.
* …
> Fix hashing of results so model caching works again

- .github/workflows/docs-build-and-deploy.yml
* Fix syntax error in workflow YAML
Problem was permissions were being set twice. It was causing a workflow to fail.
None.
None.
> Remove GitHub workflow redundant permissions

- src/matchbox/server/postgresql/alembic.ini
This changes the logging formatting for alembic to follow the ASIM format used for the rest of matchbox. This then optimises it for datadog also, as well as in general being good to standardise.
Simpler than I initially thought, just had to point alembic.ini to the right place.
Quite a small MR.
None.
> feature: alembic logging follows matchbox standard asim formatting

- src/matchbox/client/dags.py
- test/client/test_dags.py
In later pipelines we may have multiple values for one field. Array aggregation from query helps us process them.
* Adds combine type arg to `StepInput`
None.
Heavily used, but all reviewed.
None.
> Add combine type argument to StepInput.

- src/matchbox/common/sources.py
We're still getting weird connection issues. This ensures `RelationalDBLocation.head()` always exhausts `RelationalDBLocation.execute()`'s generator, which @michalc recommended. Reckon it's worth a go.
* `RelationalDBLocation.head()`
None.
None.
None.
> Changed RelationalDBLocation.head() to always exhaust the generator

- src/matchbox/server/Dockerfile
Follow-up to MR https://github.com/uktrade/matchbox/pull/227 that set environment variable for dd_version but not the docker label, which I realised is also expected (see docs here https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=docker#configuration-1)
Check the docs linked.
None.
Datadog docs https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=docker#configuration-1
> bugfix: add dd_version docker label

- src/matchbox/client/results.py
`Results._merge_with_source_data()` didn't work because the left-joined column is dropped by default in polars, it seems.
* Removes the drops
None.
None.
None.
> Removes breaking drop from source data inspection

- docs/server/risks.md
- mkdocs.yml
* Transfer internal risk register to public docs
None.
Fed it my draft, made it simpler to read, I reviewed.
None
> Add risk register to docs

- src/matchbox/server/Dockerfile
- uv.lock
Add curl to the Docker image. The reason is this is useful for health checks when deployed. It could go in matchbox-deploy but my view is curl is sufficiently widely used for this purpose to the point that any open-source user would likely expect it to be there. 
If you agree and this is merged then I'll remove it from the version of matchbox-deploy I've got currently which goes together with adding these health checks on an MR in data-workspace (i.e. we want to make sure curl is there, either from matchbox or from matchbox-deploy, before that change would be applied to prod/staging or the health checks fail!).
None.
> feature: add curl as an aid to deployment healthchecks

- src/matchbox/client/_handler.py
- src/matchbox/common/exceptions.py
- test/client/helpers/test_match_helper.py
- test/client/helpers/test_query_helper.py
- uv.lock
Sometimes, for various reasons, we expect data from the server and get nothing. An example is you've used a resolution that has no access to the sources you supplied.
Often the first time you hear about this is at cleaning. This makes it so the error happens at an earlier, more informative point.
* Adds new exception for the server returning unexpectedly empty data
* Throws it in `_handler.query()` and `_handler.match()
I elected to make this a client side error, not a server side error, as in the above example the request is well-formed from the server's perspective. It's answered the question correctly. The problem was that the client asked a silly question.
Used heavily, all reviewed.
None.
> Adds exception for when we expect a server response and get nothing

- .github/workflows/deploy-docker-image-to-packages.yml
- .github/workflows/deploy-package-to-pypi.yml
- .github/workflows/docs-build-and-deploy.yml
- docs/contributing.md
We're getting a race condition in AWS CodeBuild because it builds before we've finished releasing.
The quickest fix right now is to build artefacts for a release before we trigger it from GitHub. 
* Changes all GitHub Action release triggers to be on semver tags
* Adds documentation on new release procedure
Note this won't be forever. See the ticket for more info.
None.
* [Semantic versioning](https://semver.org)
* [Syntax for detecting tags](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onpushbranchestagsbranches-ignoretags-ignore) (note: not regex)
> Changed build trigger to be adding tags so we can release post-build

- .github/workflows/release.yml
Deploy failed:
```
Run version="v0.5.6"
version="v0.5.6"
clean_version=${version#v}
if ! echo "$clean_version" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+; then
echo "Error: Version must be in format x.x.x"
exit 1
fi
final_tag="v$clean_version"
echo "tag=$final_tag" >> $GITHUB_OUTPUT
shell: /usr/bin/bash -e {0}
env:
REGISTRY: ghcr.io
IMAGE_NAME: uktrade/matchbox
/home/runner/work/_temp/81ebdde3-5b15-4ce5-99d0-a0ea5c1c185b.sh: line 4: unexpected EOF while looking for matching `''
Error: Process completed with exit code 2.
```
Fixes regex.
New code works:
```
willlangdale@DIT004003 matchbox % version="v0.5.6" && clean_version=${version#v} && if echo "$clean_version" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' >/dev/null; then echo "✅ WORKS: $clean_version is valid"; else echo "❌ BROKEN: $clean_version is …
```
> Fixed regex issue in release.yml.

- .github/workflows/release.yml
The "latest" tag wasn't moving in release, causing the wrong thing to deploy.
* Removes the accidental cherry-picking of the Docker tag, instead of using all
* Harmonises release name
Proof it works locally:
```text
(matchbox-db) DIT004003:matchbox willlangdale$ docker images ghcr.io/uktrade/matchbox
REPOSITORY                 TAG       IMAGE ID       CREATED         SIZE
ghcr.io/uktrade/matchbox   0.5.6     36ec752a6719   4 minutes ago   1.66GB
ghcr.io/uktrade/matchbox   latest    36ec752a6719   4 minutes ago   1.66GB
(matchbox-db) DIT004003:matchbox willlangdale$ docker save ghcr.io/uktrade/matchbox > /tmp/test-image.tar
(matchbox-db) DIT004003:matchbox willlangdale$ docker rmi ghcr.io/uktrade/matchbox:0.5.6 ghcr.io/uktrade/matchbox:latest || true
Untagged: …
```
> Fixed accidental removal of latest tag

- .github/workflows/prerelease.yml
- pyproject.toml
- uv.lock
The prerelease webhook isn't firing on GitHub, instead firing things like `830c1ff0-93bc-11f0-973b-f7610dc1ad8b release.edited`. AWS doesn't pick this up as a prerelease.
Also, prereleasing from a tagged version messes up the tagging of that release.
* Delete the prerelease in an effort to trigger the right event
* Uses `SETUPTOOLS_SCM_PRETEND_METADATA` so that
* If you release from a tagged commit, you still get the dev tag
* If you release from a non-tagged commit, you get the same dev tag as if you didn't use the env override
Observe:
```
(matchbox-db) DIT004003:matchbox willlangdale$ uv run --frozen python -m setuptools_scm
0.5.8.dev1+g7006f5684
(matchbox-db) DIT004003:matchbox willlangdale$ SETUPTOOLS_SCM_PRETEND_METADATA="{distance=1}" uv run --frozen python -m setuptools_scm …
```
> Make prerelease action more robust

- src/matchbox/client/sources.py
- src/matchbox/common/db.py
- test/client/test_sources.py
Extract transform couldn't handle unions. Now it can.
* Removed dead validation function
* Added extra unit test and fixed to pass
None.
None.
None.
> Fix bug with union in extract transform

- .github/workflows/prerelease.yml
Previous attempt to get pre-release to publish dev version of package to PyPi failed.
* Define step output in pre-release YAML as an attempt to fix broken workflow
None
None
* [GitHub guide on passing output between steps](https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs)
> Fix prerelease MB version identification

- .github/workflows/prerelease.yml
Remove local version label from pre-release package prior to it being pushed to PyPi. For example, remove the part after the plus sign in `0.6.3.dev51+g379cee97c.d20251007`
I tried using a way native to `setuptools_scm`, but couldn't get it to work in the CLI, and decided it wasn't worth my time.
Generated the `sed` expression.
* [Example of error I was getting](https://github.com/pypi/warehouse/issues/18348)
> Remove local version label from prereleased package
